// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkeOS4sOxR7wMIzg2dqzPqlEallVo5KHY',
    appId: '1:387764571331:web:63dc37f18a3b14952b2676',
    messagingSenderId: '387764571331',
    projectId: 'flutterfinal-f35a9',
    authDomain: 'flutterfinal-f35a9.firebaseapp.com',
    storageBucket: 'flutterfinal-f35a9.appspot.com',
    measurementId: 'G-0QN1YW14ZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdXfzJJ1dj9gn07tSoF67UwupThyBl6vQ',
    appId: '1:387764571331:android:5872787b95f82c632b2676',
    messagingSenderId: '387764571331',
    projectId: 'flutterfinal-f35a9',
    storageBucket: 'flutterfinal-f35a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB16D4EFEDFMH6EU2eFVwnsb-0hrPyRKYk',
    appId: '1:387764571331:ios:cf3dba4bd3d671c32b2676',
    messagingSenderId: '387764571331',
    projectId: 'flutterfinal-f35a9',
    storageBucket: 'flutterfinal-f35a9.appspot.com',
    iosBundleId: 'com.example.finalExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB16D4EFEDFMH6EU2eFVwnsb-0hrPyRKYk',
    appId: '1:387764571331:ios:cf3dba4bd3d671c32b2676',
    messagingSenderId: '387764571331',
    projectId: 'flutterfinal-f35a9',
    storageBucket: 'flutterfinal-f35a9.appspot.com',
    iosBundleId: 'com.example.finalExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkeOS4sOxR7wMIzg2dqzPqlEallVo5KHY',
    appId: '1:387764571331:web:70bab2fcdcdea24b2b2676',
    messagingSenderId: '387764571331',
    projectId: 'flutterfinal-f35a9',
    authDomain: 'flutterfinal-f35a9.firebaseapp.com',
    storageBucket: 'flutterfinal-f35a9.appspot.com',
    measurementId: 'G-PRHD5GT9LK',
  );
}
